### ISSUE TITLE
[PVP] Disable it.

### ISSUE THREAD

**Issue by TheIntelloBox** [NiklasEi/GameBox_ConnectFour#1]
Hi !

When a player hit me, it says : "You left the game".
Could you disable it ?

Thanks !

**Comment by NiklasEi** [comment]
I am doing that on purpose. When a player gets attacked while he is in a GameBox GUI or in a game, the inventory is closed. Players are supposed to be in a save place when playing. 

I can add an option to allow for damage while playing.

**Comment by NiklasEi** [comment]
Plus this is done by GameBox. You can reopen the issue for GameBox and I'll close this one. 

I'll put the additional option on my Todo list.
